server:
    port: 8081

spring:
    application: 
        name: employee-service
    datasource:
        url: jdbc:mysql://monorail.proxy.rlwy.net:3306/railway?useSSL=false&serverTimezone=UTC&uaseLegacyDatetimeCode=false
        username:  root
        password: 1G2gd3EdEC2G4g4a4BA6h6ddge3dbBB2
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate: 
            ddl-auto: update
        show-sql: true
        properties: 
            hibernate: 
                dialect: org.hibernate.dialect.MySQLDialect
                format_sql: true
                default_schema: railway
    config: 
        import: "optional:configserver:http://localhost:9002"
    cloud:
        config:
            name: employee
            discovery: 
                enabled: true
                service-id: config-server


eureka:
    client:
         service-url:
            defaultZone: http://localhost:9001/eureka
    instance:
        prefer-ip-address: true
